config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  root 'static_pages#home'

  get '/archive', to: 'static_pages#archive'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, except: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
  validates :body, presence: true, length: {maximum: 355}
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save {self.email = email.downcase}
  before_create :create_activation_digest
  validates :name, presence: true, length: {maximum: 50},
  uniqueness: {case_sensitive: false, message: 'Пользователь с именем %{value} уже существует.'}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}

  # Returns the hash digest of the given string (user.remember)
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    # Rails.logger.info "Called user.remember"
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  def session_token
    remember_digest || remember
  end

  # Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Activates account
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def appear
    unless $redis.hset("u_ol", self.name, self.id) == 0
      data = { action: "appear", appeared_user: self.name }
      Rails.logger.info "APPEAR METHOD sent data: #{data.inspect} time: #{Time.now}"
      ActionCable.server.broadcast("appearance_channel", data)
    end
  end

  def disappear
    $redis.hdel("u_ol", self.name)
    data = { action: "disappear", disappeared_user: self.name }
    Rails.logger.info "DISAPPEAR METHOD CALLED for #{self.name} time: #{Time.now}"
    ActionCable.server.broadcast("appearance_channel", data)
  end

  private

  # Creates and assigns the activation token and digest
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  # Confirms a logged-in user
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "You must be logged in"
      redirect_to login_url
    end 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      forwarding_url = session[:forwarding_url]
      reset_session
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      log_in user
      redirect_to forwarding_url || root_url
    else
      flash.now[:danger] = "Wrong combination email/password!"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @users_online = $redis.hkeys('u_ol')
    @chatroom = Chatroom.last
    @messages = Message.where(chatroom_id: @chatroom.id).includes(:user)
  end

  def archive
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Account created successfully!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user
  def log_in(user)
    # for use in ActionCable connect methog
    cookies.encrypted[:user_name] = user.name
    session[:user_id] = user.id
    session[:session_token] = user.session_token
  end

  # Remember a user in a persistent session
  def remember(user)
    user.remember
    Rails.logger.info "CALLED REMEMBER USER"
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  #Returns the user corresponding to the remember token cookie
  def current_user
    if (user_id = session[:user_id])
      user = User.find_by(id: user_id)
      if user && session[:session_token] == user.session_token
        @current_user = user
      end
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user?(user)
    user == current_user
  end

  # Forgets a persistent session
  def forget(user)
    user.forget
    cookies.delete(:user_name)
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Returns true if the user is logged-in, false otherwise
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user
  def log_out
    forget(current_user)
    reset_session
    @current_user = nil
  end

  # Stores the URL trying to be accessed
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer d-flex justify-content-center">
  <div class="d-flex flex-column">
    <div class="d-flex justify-content-center">
      <small>
        Link to the repository: 
      </small>
      <span>
      <a href="https://bitbucket.org/stgmft/apm_radio/src/master/"> 
      <svg viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg" focusable="false" aria-hidden="true">
        <defs>
          <linearGradient x1="100%" x2="45.339%" y1="29.23%" y2="75.038%" id="uid25">
            <stop stop-color="inherit" stop-opacity="0.4" offset="0%"></stop>
            <stop stop-color="inherit" offset="100%"></stop>
          </linearGradient>
        </defs>
        <g stroke="none" stroke-width="1" fill-rule="nonzero">
          <path d="M4.78580435,5 C4.55423538,4.99701333 4.33319771,5.09657765 4.18198458,5.27198488 C4.03077145,5.44739211 3.96486141,5.68068714 4.00193478,5.9092887 L7.32946109,26.1096074 C7.3703589,26.355373 7.49665951,26.578828 7.68612174,26.7406224 C7.87680866,26.9055104 8.11992598,26.9972003 8.37200761,26.9992993 L14.5488998,19.5995707 L13.6827239,19.5995707 L12.3227102,12.3958093 L27.3886833,12.3958093 L28.4469072,5.91712739 C28.4862006,5.68935393 28.4229655,5.45584955 28.2741046,5.27903 C28.1252437,5.10221045 27.9059335,5.00010264 27.6747957,5 L4.78580435,5 Z" fill="currentColor"></path>
          <path fill="url(#uid25)" d="M27.3886833,12.3958093 L20.0320674,12.3958093 L18.7974728,19.5995707 L13.7023207,19.5995707 L7.68612174,26.7445417 C7.87680866,26.9094297 8.11992598,27.0011197 8.37200761,27.0032187 L24.3394307,27.0032187 C24.727754,27.0082167 25.0611955,26.7281258 25.1233002,26.3447683 L27.3886833,12.3958093 Z"></path>
        </g>
      </svg> Bitbucket
      </a>
    </div>
    <div class="d-flex justify-content-center mt-1">
      <small>LinkedIn:</small>
      <a href="https://www.linkedin.com/in/andrei-zheksim/">
      <%= image_tag "linkedin.png", loading: 'lazy', alt: 'linkedIn', height: '26', width: '26' %>
      </a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">

  <%= link_to "Apm-radio", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Archive", archive_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Account", current_user, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Logout", logout_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle ml-auto" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Authorisation
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Sign up", signup_path, class: "dropdown-item" %>
            <%= link_to "Sign in", login_path, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
<!-- RADIO -->
<div class="topRadioHolder">
  <%# <audio preload="auto" class="d-none" controls>
    <source src="https://podcast-media.zenolive.com/media/agxzfnplbm8tc3RhdHNyFgsSCU1lZGlhSXRlbRiAgLDq1InUCwyiAQdsaWJyYXJ5.mp3">
  </audio> %>

</div> 

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | APM radio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%# Styles %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'     %>
    <%# Fonts %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,300&family=Rajdhani:wght@400;500;600;700&family=Titillium+Web:wght@300;400;700;900&display=swap" rel="stylesheet"> 
    <%# JavaScript %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container content-wrapper">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
     <div class="bottomRadioHolder"></div>
      <%# <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/_chat.html.erb
<!--chat layout -->
<div class="pc-tab col-md-9">
  <input checked="checked" id="tab1" type="radio" name="pct" />
  <input id="tab2" type="radio" name="pct" />
  <nav>
    <ul>
      <li class="tab1">
        <label for="tab1">Online</label>
      </li>
      <li class="tab2">
        <label for="tab2" id="tab2">Messages</label>
      </li>
    </ul>
  </nav>

  <section>
    <!-- users online -->
    <div class="tab1 radiochat container-fluid" data-current-user="<%= current_user.name %>">
      <!-- chat controls -->
      <div class="chat-ctrls my-0 d-flex justify-content-end">
        <h6 class="mr-auto mt-2">Users online</h6>
        <span class="roll_up mr-2">&nbsp;&nbsp;&nbsp;</span>
        <button type="button" class="close" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <ul class="users-online list-group list-group-flush" data-turbolinks-permanent>
        <% @users_online.each do |user| %>
          <!-- user from "u_ol" hash -->
          <li class="list-group-item">
            <a href="#">
              <div class="d-flex flex-row">
                <div class="avatar mr-2">MH</div><span class="my-auto"><%= user %></span>
              </div>
            </a>
          </li>
        <% end %>
      </ul>

    </div>
    <!-- chat body -->
    <div class="tab2 radiochat container-fluid" id="radiochat">
      <!-- chat controls -->
      <div class="chat-ctrls my-0 d-flex justify-content-end">
        <span class="roll_up mr-3">&nbsp;&nbsp;&nbsp;</span>
        <button type="button" class="close" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% @messages.each do |message| %>
        <% if message.user.name != current_user.name %>
        <!-------- LEFT MESSAGE ------------------------>
          <div class="row left d-flex flex-row">
            <div class="wrapper d-flex mx-2">
              <div class="left-avatar align-self-center">WM</div>
            </div>
            <div class="text w-75">
              <h4><%= message.user.name %></h4>
              <div class="status online"></div>
              <p class="msg-text">
                <%= message.body %>
              </p>
            </div>
          </div>
        <% else %>
        <!-----------       RIGHT MESSAGE    ---------------->
        <div class="row right d-flex justify-content-end">
          <div class="text w-75 text-right">
            <h4><%= message.user.name %></h4>
            <p class="msg-text">
              <%= message.body %>
            </p>
          </div>
          <div class="wrapper d-flex mx-2">
            <div class="right-avatar align-self-center" style="border-color: #eed610;">RW</div>
          </div>
          <div class="col-2 col-sm-4"></div>
        </div>
        <% end %>
      <% end %>
      <!-- empty message (strip) -->
      <div class="strip w-100"></div>
      <!-------------------- MESSAGE INPUT --------->
      <div class="w-100 msg-input">
        
        <form class="chat-msg" action="#" method="post">
          <div class="input-group">
          <!------------------    INPUT TEXTAREA                      ------------------>
            <input type="text" class='form-control message-input' %>
              
            <div class="input-group-append">
              <button class="btn send-button" type="button">Send</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </section>
</div>

app/views/static_pages/_newscards.html.erb
<!-- News cards --->
 <div class="container">
    <div class="news row mt-4">
      <div class="news-card col-12 col-md-4" >
        <div class="news-img">
          <%= image_tag 'architect-1.jpg', loading: 'lazy', alt: 'news' %>
        </div>
        <div class="news-body">
        <h3 class="text-center">New architectural designs</h3>
        <p class="news-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nihil fugit possimus et id eligendi aliquam nostrum impedit distinctio praesentium, </p>
        </div>
      </div>
      <div class="news-card col-12 col-md-4" >
        <div class="news-img">
          <%= image_tag 'architect-2.jpg', loading: 'lazy', alt: 'news' %>
        </div>
        <div class="news-body">
          <h3 class="text-center">Norwegian expression of the day: Det skulle bare mangle </h3>
          <p class="news-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nihil fugit possimus et id eligendi aliquam nostrum impedit distinctio praesentium</p>
        </div>
      </div>
      <div class="news-card col-12 col-md-4" >
        <div class="news-img">
          <%= image_tag 'bird.jpg', loading: 'lazy', alt: 'news' %>
        </div>
        <div class="news-body">
          <h3 class="text-center">Away from it all: Pure adventure cruising around Chilean Patagonia</h3>
          <p class="news-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nihil fugit possimus et</p>
        </div>
      </div>
    </div>
        
    <div class="news row mt-4">
      <div class="news-card col-12 col-md-4" >
        <div class="news-img">
          <%= image_tag 'deers.jpg', loading: 'lazy', alt: 'news' %> 
        </div>
        <div class="news-body">
        <h3 class="text-center">Winter Hike in Yosemite Valley </h3>
        <p class="news-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nihil fugit possimus et id eligendi aliquam nostrum impedit distinctio praesentium, facere, enim, nulla ut quibusdam porro repellat sequi commodi voluptates rerum.</p>
        </div>
      </div>
      <div class="news-card col-12 col-md-4" >
        <div class="news-img">
          <%= image_tag 'koala-1.png', loading: 'lazy', alt: 'news' %>
        </div>
        <div class="news-body">
        <h3 class="text-center">Triumph the new koala who was born in Tokyo zoo</h3>
        <p class="news-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nihil fugit possimus et id eligendi aliquam nostrum impedit </p>
        </div>
      </div>
      <div class="news-card col-12 col-md-4" >
        <div class="news-img">
          <%= image_tag 'koala-5.jpg', loading: 'lazy', alt: 'news' %>
        </div>
        <div class="news-body">
          <h3 class="text-center">Koalas: Australia lists marsupial as endangered species</h3>
          <p class="news-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nihil fugit possimus et id eligendi aliquam nostrum impedit </p>
        </div>
      </div>
    </div>
  </div>

app/views/static_pages/archive.html.erb
<% provide(:title, "Архив") %>
<h1 style="margin-top:2rem">Archive</h1>
<p>You can put here links on your podacsts</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Main") %>
<!-- chat and chat sidebar -->
<div class="container-fluid mb-3 home-container">

    <% if logged_in? %>
      <!-- Радиочат -->
      <%= render 'static_pages/chat.html.erb' %>
    <% else %>
    <div class="container">
      <div class="header row d-flex justify-content-center align-items-center">
        <h2 class="px-5 col-10 col-lg-6 text-center">
          Welcome to the first interactive radio. Activate chat to participate in
          discussion.
        </h2>
        <div class="col-12 d-flex justify-content-center" >
          <%= link_to "Activate chat", login_path, class: "activate" %> 
        </div>
      </div>
    </div>
    <% end %>
    <!-------------- NEWS CARDS --------------->
    <%= render 'static_pages/newscards.html.erb' %>

</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="auth container pt-4 mt-3">

  <h1 class="mt-4">Create new account</h1>

  <div class="row justify-content-center">
    <div class="col-10 col-md-5 mx-auto">
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control auth-input' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control auth-input' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control auth-input' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control auth-input' %>

        <div class="row justify-content-center my-3">
          <%= f.submit "Sign up", class: "btn btn-primary mt-2" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Account") %> 

<%= @user.name %>, <%= @user.email %>